name: deb-package

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - name: install git
        run: |
          sudo apt-get update && sudo apt-get install -y git
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            ocs2_msgs ocs2_thirdparty ocs2_core ocs2_oc ocs2_mpc ocs2_ddp ocs2_sqp ocs2_test_tools/ocs2_qp_solver ocs2_robotic_tools blasfeo_catkin hpipm_catkin 
      - uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: noetic
      - name: Add temp rosdep index
        run: |
          echo "yaml file://`pwd`/rosdep.yaml" | sudo tee /etc/ros/rosdep/sources.list.d/ocs2.list
          sudo rosdep update
      - name: Package deb
        uses: gdut-dynamic-x/ros-build-deb-action@v1
        with:
          ros_distro: noetic
          timestamp: true
      - name: Upload deb package to source
        if: ${{ github.repository == 'gdut-dynamic-x/ocs2' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          source: "*.deb"
          target: "/usr/local/web/rm-source/ubuntu/incoming/"
      - name: Deploy deb package to source
        if: ${{ github.repository == 'gdut-dynamic-x/ocs2' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOURCE_SSH_HOST }}
          username: ${{ secrets.SOURCE_SSH_NAME }}
          key: ${{ secrets.SOURCE_SSH_KEYGEN }}
          script: |
                  cd /usr/local/web/rm-source/ubuntu/incoming/
                  reprepro  -s  -b  /usr/local/web/rm-source/ubuntu/  --waitforlock  1000  includedeb focal /usr/local/web/rm-source/ubuntu/incoming/*.deb && \
                  rm -f *.deb
